# -*- coding: utf-8 -*-
import os
FILES={}
FILES['food/singapore/restaurants/mouth-restaurant-di-mao-guan/index.md']='---\nlayout: default\nsection: food\nreview: true\ntitle: Mouth Restaurant - 地茂馆 (Di Mao Guan)\nsubtitle: Maxwell / Chinatown · Dim Sum, Cantonese\n---\n\nVery good choice for upscale dim sum in Chinatown with a particularly impressive variety of steamed dumplings. Prices are definitely on the high side, but the quality justifies them. The siomai are especially excellent.\n\n## Ratings\n\n| Category        | Score  |\n| --------------- | ------ |\n| Food            | 8.5/10 |\n| Service         | 7.5/10 |\n| Value for money | 7/10 |\n| Atmosphere      | 7.5/10 |\n| Overall         | 8/10 |\n\n### Practical\n\n🗺️ **Google Maps:** [Open in Google Maps](https://www.google.com/maps/search/?api=1&query=Mouth+Restaurant+Di+Mao+Guan+38+Maxwell+Rd+Singapore)\n📍 38 Maxwell Rd, #01-01/02 Airview Building, Singapore 069116\n🍽️ **Type:** Dim Sum, Cantonese\n💰 **Price level:** S$20–40\n'
FILES['food/singapore/restaurants/singapore-zam-zam-restaurant/index.md']='---\nlayout: default\nsection: food\nreview: true\ntitle: Singapore Zam Zam Restaurant\nsubtitle: Kampong Glam · Indian-Muslim\n---\n\nOld-school Muslim restaurant serving huge portions at very reasonable prices by Singapore standards. The biryani comes with a generous piece of tender mutton and even a small murtabak is large enough to satisfy two hungry people.\n\n## Ratings\n\n| Category        | Score  |\n| --------------- | ------ |\n| Food            | 8/10 |\n| Service         | 7/10 |\n| Value for money | 9/10 |\n| Atmosphere      | 7/10 |\n| Overall         | 8/10 |\n\n### Practical\n\n🗺️ **Google Maps:** [Open in Google Maps](https://www.google.com/maps/search/?api=1&query=Singapore+Zam+Zam+Restaurant+697+North+Bridge+Rd)\n📍 697-699 North Bridge Rd, Singapore 198675\n🍽️ **Type:** Indian-Muslim\n💰 **Price level:** S$5–15\n'
FILES['food/singapore/restaurants/index.md']='---\nlayout: default\nsection: food\ncity: singapore\ncategory: restaurants\nslug: singapore restaurants\ntitle: Restaurants\nsubtitle: Restaurants in Singapore\n---\n\n# Restaurants in Singapore\n\n---\n\n## Mouth Restaurant - 地茂馆\n*Maxwell / Chinatown · Dim Sum, Cantonese*\nVery good upscale dim sum in Chinatown with an impressive variety of steamed dumplings; pricey, but the quality justifies it.\n→ [Read the full review](/food/singapore/restaurants/mouth-restaurant-di-mao-guan/)\n\n---\n## Singapore Zam Zam Restaurant\n*Kampong Glam · Indian-Muslim*\nOld-school Indian-Muslim spot with huge portions at reasonable prices; a generous mutton biryani and a filling murtabak.\n→ [Read the full review](/food/singapore/restaurants/singapore-zam-zam-restaurant/)\n\n---\n'
FILES['food/singapore/index.md']='---\nlayout: default\nsection: food\ncountry: singapore\ntitle: Singapore\nsubtitle: Food & drink in Singapore\n---\n\n# Singapore\n\nFood & drink in Singapore.\n\n## Restaurants\n- [Restaurants](/food/singapore/restaurants/)\n'
FILES['food/index.md']='---\nlayout: default\nsection: food\nindex: true\nslug: food\n---\n\n\n\n# Food\n\nCountries covered \n\n## Asia\n\n- [Thailand](/food/thailand/)\n- [Vietnam](/food/vietnam/)\n- [Philippines](/food/philippines/)\n- [Malaysia](/food/malaysia/)\n- [Indonesia](/food/indonesia/)\n- [Laos](/food/laos/)\n- [Cambodia](/food/cambodia/)\n- [India](/food/india/)\n- [Taiwan](/food/taiwan/)\n- [Singapore](/food/singapore/)\n\n## Europe\n\n- [Austria](/food/austria/)\n- [Germany](/food/germany/)\n- [France](/food/france/)\n- [Spain](/food/spain/)\n- [Portugal](/food/portugal/)\n- [Greece](/food/greece/)\n- [Hungary](/food/hungary/)\n- [Czechia](/food/czechia/)\n- [Slovakia](/food/slovakia/)\n- [Poland](/food/poland/)\n'

for rel,content in FILES.items():
    os.makedirs(os.path.dirname(rel),exist_ok=True)
    open(rel,'w',encoding='utf-8',newline='\n').write(content); print("wrote",rel)
rp="reviews-without-photos.txt"
if os.path.exists(rp):
    L=[x.strip() for x in open(rp,encoding='utf-8') if x.strip()]
    add=['food/singapore/index.md','food/singapore/restaurants/index.md',
         'food/singapore/restaurants/mouth-restaurant-di-mao-guan/index.md',
         'food/singapore/restaurants/singapore-zam-zam-restaurant/index.md']
    L=sorted(set(L)|set(add))
    open(rp,'w',encoding='utf-8',newline='\n').write('\n'.join(L)+'\n'); print('without-photos ->',len(L))
print("DONE")
